spring.application.name=sales-system

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/sales_system?ssl=false
spring.datasource.username=developer
spring.datasource.password=cerber0
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate properties
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
